<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>nl.uu.cs.is.apapl</groupId>
    <artifactId>apapl</artifactId>
    <version>1.0</version>

    <licenses>
        <license>
            <name>GNU General Public License v3.0</name>
            <url>https://spdx.org/licenses/GPL-3.0.html</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <properties>
        <start-class>nl.uu.cs.is.apapl.APAPL</start-class>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <exec.mainClass>nl.uu.cs.is.apapl.APAPL</exec.mainClass>
    </properties>

    <dependencies>
        <dependency>
            <groupId>JIProlog</groupId>
            <artifactId>JIProlog</artifactId>
            <version>1.0.0</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>http</groupId>
            <artifactId>http</artifactId>
            <version>1.0.0</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>iiop</groupId>
            <artifactId>iiop</artifactId>
            <version>1.0.0</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>jade</groupId>
            <artifactId>jade</artifactId>
            <version>1.0.0</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>jadeTools</groupId>
            <artifactId>jadeTools</artifactId>
            <version>1.0.0</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>

    <packaging>jar</packaging>
    <name>2APL: A Practical Agent Programming Language</name>
    <description>2APL (pronounced as double-a-p-l) is an agent-oriented programming language that facilitates the
        implementation of multi-agent systems. At the multi-agent level, it provides programming constructs to
        specify a multi-agent system in terms of a set of individual agents and a set of environments in which
        they can perform actions. At the individual agent level, it provides programming constructs to implement
        cognitive agents based on the BDI architecture. In particular, it provides programming constructs to
        implement an agent’s beliefs, goals, plans, actions (such as belief updates, external actions, or
        communication actions), events, and a set of rules through which the agent can decide which actions to
        perform. 2APL is a modular programming language allowing the encapsulation of cognitive components in
        modules. 2APL supports the implementation of both reactive and pro-active agents.</description>

    <contributors>
        <contributor>
            <name>Mehdi Dastani</name>
            <email>M.M.Dastani@uu.nl</email>
            <url>https://www.uu.nl/staff/MMDastani</url>
        </contributor>
        <contributor>
            <name>Bas Testerink</name>
            <email> B.J.G.Testerink@uu.nl</email>
            <url>https://www.uu.nl/staff/BJGTesterink</url>
        </contributor>
        <contributor>
            <name>Michal Cap</name>
        </contributor>
        <contributor>
            <name>Tristan Behrans</name>
        </contributor>
    </contributors>

    <organization>
        <name>Intelligent Systems, Utrecht University</name>
        <url>https://www.uu.nl/en/research/artificial-intelligence/intelligent-systems</url>
    </organization>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.3.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <descriptorRefs>
                                <descriptorRef>jar-with-dependencies</descriptorRef>
                            </descriptorRefs>
                            <archive>
                                <manifest>
                                    <mainClass>nl.uu.cs.is.apapl.APAPL</mainClass> <!-- Substitua pela sua classe principal -->
                                </manifest>
                            </archive>
                        </configuration>
                    </execution>
                </executions>
            </plugin>   
        
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>2.4</version>
                <executions>
                    <execution>
                        <id>blockworld-environment</id>
                        <goals><goal>jar</goal></goals>
                        <phase>package</phase>
                        <configuration>
                            <finalName>blockworld</finalName>
			<archive>
   				 <manifest>
       					 <mainClass>nl.uu.cs.is.apapl.environments.blockworld.Env</mainClass>
    				</manifest>
			</archive>
                            <includes>
                                <include>nl/uu/cs/is/apapl/environments/blockworld/*.class</include>
                                <include>nl/uu/cs/is/apapl/environments/blockworld/lib/*</include>
                                <include>nl/uu/cs/is/apapl/environments/blockworld/images/*</include>
                            </includes>
                        </configuration>
                    </execution>

                    <execution>
                        <id>simple-environment</id>
                        <goals><goal>jar</goal></goals>
                        <phase>package</phase>
                        <configuration>
                            <finalName>env</finalName>
                            <archive>
                                <manifestFile>src/main/resources/META-INF/simple/Manifest.txt</manifestFile>
                            </archive>
                            <includes>
                                <include>nl/uu/cs/is/apapl/environments/simple/*</include>
                            </includes>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.0.1</version>
                <executions>
                    <execution>
                        <id>copy-blockworld-to-explorer-and-carry</id>
                        <phase>install</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${basedir}/examples/explorer and carrier</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${project.build.directory}</directory>
                                    <include>blockworld.jar</include>
                                    <filtering>false</filtering>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>

                    <execution>
                        <id>copy-blockworld-to-harry-and-sally</id>
                        <phase>install</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${basedir}/examples/harry and sally</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${project.build.directory}</directory>
                                    <include>blockworld.jar</include>
                                    <filtering>false</filtering>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>

                    <execution>
                        <id>copy-env-to-basic</id>
                        <phase>install</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${basedir}/examples/basic 2apl setup</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${project.build.directory}</directory>
                                    <include>env.jar</include>
                                    <filtering>false</filtering>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>

                    <execution>
                        <id>copy-env-to-ircbot</id>
                        <phase>install</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${basedir}/examples/ircbot</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${project.build.directory}</directory>
                                    <include>env.jar</include>
                                    <filtering>false</filtering>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>

        <resources>
            <resource>
                <directory>src/main/java/nl/uu/cs/is/apapl/gui/icons</directory>
                <targetPath>${project.build.outputDirectory}/nl/uu/cs/is/apapl/gui/icons</targetPath>
            </resource>
            <resource>
                <directory>src/main/java/nl/uu/cs/is/apapl/environments/blockworld/images</directory>
                <targetPath>${project.build.outputDirectory}/nl/uu/cs/is/apapl/environments/blockworld/images</targetPath>
            </resource>
            <resource>
                <directory>src/main/resources/license</directory>
                <targetPath>${project.build.outputDirectory}</targetPath>
            </resource>
        </resources>
    </build>
</project>
